#!/bin/bash
# Name: post-receive
# Author: Rachel Shaw <rshaw@beijaflor.es>
# Last Updated: 2021-06-16
#
# Description: 
# Post-receive git hook meant to automatically clone repository and perform
# deployment tasks.
#
# Intended location of file on production server:
#
#     ~/beijaflor.es.git/hooks/post-receive
# 
# NOTE: This file should be executable by the current user, such as via
#
#     $ chmod +x post-receive
#

# Specify the zola version you want to use here
ZOLA_VERSION="v0.13.0"

PUBLIC_URL=https://beijaflor.es
GIT_REPO=$HOME/beijaflor.es.git
DEST_DIR=/var/www/html/
TMP_GIT_CLONE=`mktemp -d`

echo "Cloning repository to ${TMP_GIT_CLONE}..."
git clone --recurse-submodules -j8 $GIT_REPO ${TMP_GIT_CLONE}
cd ${TMP_GIT_CLONE}

echo "Copying over this post-receive hook..."
cp ${TMP_GIT_CLONE}/hooks/post-receive ${GIT_REPO}/hooks/

echo "Downloading zola..."
curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz

echo "Building site with zola..."
tar xzvf zola.tar.gz
./zola build -o $DEST_DIR || (echo "Failed to build site, exiting..." && exit 1)

echo "Reloading Apache2 config..."
sudo /usr/sbin/service apache2 reload

echo "Deleting temporary directory ${TMP_GIT_CLONE}..."
rm -rf $TMP_GIT_CLONE

echo "Done!  Your site is now publicly available at: "
echo "${PUBLIC_URL}"
exit
